//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opsControlCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALARMS
    {
        public decimal ALA_ID { get; set; }
        public decimal ALA_DALA_ID { get; set; }
        public decimal ALA_UNI_ID { get; set; }
        public System.DateTime ALA_INIDATE { get; set; }

        public virtual UNITS UNITS { get; set; }
        public virtual ALARMS_DEF ALARMS_DEF { get; set; }

    }
}
