//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opsControlCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLLECTINGS
    {
        public decimal COL_ID { get; set; }
        public decimal COL_UNI_ID { get; set; }
        public decimal COL_NUM { get; set; }
        public Nullable<System.DateTime> COL_DATE { get; set; }
        public System.DateTime COL_INIDATE { get; set; }
        public System.DateTime COL_ENDDATE { get; set; }
        public decimal COL_BACK_COL_TOTAL { get; set; }
        public decimal COL_CASH_PARK { get; set; }
        public decimal COL_CASH_FINE { get; set; }
        public decimal COL_CASH_RECHARGE { get; set; }
        public decimal COL_CASH_TOTAL { get; set; }
        public decimal COL_CASH_PARK_OPS { get; set; }
        public decimal COL_CASH_FINE_OPS { get; set; }
        public decimal COL_CASH_RECHARGE_OPS { get; set; }
        public decimal COL_CASH_TOTAL_OPS { get; set; }
        public decimal COL_CRCARD_PARK { get; set; }
        public decimal COL_CRCARD_FINE { get; set; }
        public decimal COL_CRCARD_RECHARGE { get; set; }
        public decimal COL_CRCARD_TOTAL { get; set; }
        public decimal COL_CRCARD_PARK_OPS { get; set; }
        public decimal COL_CRCARD_FINE_OPS { get; set; }
        public decimal COL_CRCARD_RECHARGE_OPS { get; set; }
        public decimal COL_CRCARD_TOTAL_OPS { get; set; }
        public decimal COL_CHCARD_PARK { get; set; }
        public decimal COL_CHCARD_FINE { get; set; }
        public decimal COL_CHCARD_RETURN { get; set; }
        public decimal COL_CHCARD_TOTAL { get; set; }
        public decimal COL_CHCARD_PARK_OPS { get; set; }
        public decimal COL_CHCARD_FINE_OPS { get; set; }
        public decimal COL_CHCARD_RETURN_OPS { get; set; }
        public decimal COL_CHCARD_TOTAL_OPS { get; set; }
        public decimal COL_CMI_050 { get; set; }
        public decimal COL_CMI_050_075 { get; set; }
        public decimal COL_CMI_075_100 { get; set; }
        public decimal COL_CMI_100_075 { get; set; }
        public decimal COL_CMI_150_075 { get; set; }
        public decimal COL_CMI_200_075 { get; set; }
        public decimal COL_CMI_250_075 { get; set; }
        public decimal COL_CMI_300_075 { get; set; }
        public decimal COL_CMI_400_075 { get; set; }
        public decimal COL_CMI_500 { get; set; }
        public decimal COL_CTI_1000 { get; set; }
        public decimal COL_CTI_1000_1200 { get; set; }
        public decimal COL_CTI_1200_1400 { get; set; }
        public decimal COL_CTI_1400_1600 { get; set; }
        public decimal COL_CTI_1600_1800 { get; set; }
        public decimal COL_CTI_1800_2000 { get; set; }
        public decimal COL_CTI_2000_2200 { get; set; }
        public decimal COL_CTI_2200_0000 { get; set; }
        public decimal COL_CASH_COINS_V1 { get; set; }
        public decimal COL_CASH_COINS_Q1 { get; set; }
        public decimal COL_CASH_COINS_V2 { get; set; }
        public decimal COL_CASH_COINS_Q2 { get; set; }
        public decimal COL_CASH_COINS_V3 { get; set; }
        public decimal COL_CASH_COINS_Q3 { get; set; }
        public decimal COL_CASH_COINS_V4 { get; set; }
        public decimal COL_CASH_COINS_Q4 { get; set; }
        public decimal COL_CASH_COINS_V5 { get; set; }
        public decimal COL_CASH_COINS_Q5 { get; set; }
        public decimal COL_CASH_COINS_V6 { get; set; }
        public decimal COL_CASH_COINS_Q6 { get; set; }
        public decimal COL_CASH_COINS_V7 { get; set; }
        public decimal COL_CASH_COINS_Q7 { get; set; }
        public decimal COL_CASH_COINS_V8 { get; set; }
        public decimal COL_CASH_COINS_Q8 { get; set; }
        public decimal COL_CASH_COINS_V9 { get; set; }
        public decimal COL_CASH_COINS_Q9 { get; set; }
        public decimal COL_CASH_COINS_V10 { get; set; }
        public decimal COL_CASH_COINS_Q10 { get; set; }
        public decimal COL_CASH_COINS_V11 { get; set; }
        public decimal COL_CASH_COINS_Q11 { get; set; }
        public decimal COL_CASH_COINS_V12 { get; set; }
        public decimal COL_CASH_COINS_Q12 { get; set; }
        public decimal COL_CASH_COINS_V13 { get; set; }
        public decimal COL_CASH_COINS_Q13 { get; set; }
        public decimal COL_CASH_COINS_V14 { get; set; }
        public decimal COL_CASH_COINS_Q14 { get; set; }
        public decimal COL_CASH_COINS_V15 { get; set; }
        public decimal COL_CASH_COINS_Q15 { get; set; }
        public decimal COL_COIN_REP_FACTOR { get; set; }
        public string COL_COIN_SYMBOL { get; set; }
        public Nullable<decimal> COL_CASH_RESPAY { get; set; }
        public Nullable<decimal> COL_CASH_POWRECHARGE { get; set; }
        public Nullable<decimal> COL_CASH_BYCING { get; set; }
        public Nullable<decimal> COL_CASH_RESPAY_OPS { get; set; }
        public Nullable<decimal> COL_CASH_POWRECHARGE_OPS { get; set; }
        public Nullable<decimal> COL_CASH_BYCING_OPS { get; set; }
        public Nullable<decimal> COL_CRCARD_RESPAY { get; set; }
        public Nullable<decimal> COL_CRCARD_POWRECHARGE { get; set; }
        public Nullable<decimal> COL_CRCARD_BYCING { get; set; }
        public Nullable<decimal> COL_CRCARD_RESPAY_OPS { get; set; }
        public Nullable<decimal> COL_CRCARD_POWRECHARGE_OPS { get; set; }
        public Nullable<decimal> COL_CRCARD_BYCING_OPS { get; set; }
        public Nullable<decimal> COL_CHCARD_RESPAY { get; set; }
        public Nullable<decimal> COL_CHCARD_POWRECHARGE { get; set; }
        public Nullable<decimal> COL_CHCARD_BYCING { get; set; }
        public Nullable<decimal> COL_CHCARD_RESPAY_OPS { get; set; }
        public Nullable<decimal> COL_CHCARD_POWRECHARGE_OPS { get; set; }
        public Nullable<decimal> COL_CHCARD_BYCING_OPS { get; set; }
        public Nullable<decimal> COL_NUM_COUPONS { get; set; }
        public Nullable<decimal> COL_COUPONS_VALUE { get; set; }
        public Nullable<decimal> COL_COUPONS_DURATION { get; set; }
    
        public virtual UNITS UNITS { get; set; }
    }
}
