//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opsControlCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINES_STATUS_DEF
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public FINES_STATUS_DEF()
        //{
        //    this.FINES = new HashSet<FINES>();
        //}
    
        public decimal DSFIN_ID { get; set; }
        public string DSFIN_DESCSHORT { get; set; }
        public string DSFIN_DESCLONG { get; set; }
        public decimal DSFIN_VERSION { get; set; }
        public decimal DSFIN_VALID { get; set; }
        public decimal DSFIN_DELETED { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<FINES> FINES { get; set; }
    }
}
