//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opsControlCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINES_DEF
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public FINES_DEF()
        //{
        //    this.FINES = new HashSet<FINES>();
        //}
    
        public decimal DFIN_ID { get; set; }
        public Nullable<decimal> DFIN_COD_ID { get; set; }
        public string DFIN_DESCSHORT { get; set; }
        public string DFIN_DESCLONG { get; set; }
        public decimal DFIN_VALUE { get; set; }
        public bool DFIN_STATUS { get; set; }
        public Nullable<decimal> DFIN_SIGN { get; set; }
        public decimal DFIN_PAYINPDM { get; set; }
        public decimal DFIN_NUMTICKETS { get; set; }
        public decimal DFIN_VERSION { get; set; }
        public decimal DFIN_VALID { get; set; }
        public decimal DFIN_DELETED { get; set; }
        public decimal DFIN_POSTPAYABLE { get; set; }
        public decimal DFIN_FINID_OFFSET { get; set; }
        public Nullable<decimal> DFIN_PAY_DDAY_ID { get; set; }
        public string DFIN_PDM_LIT_ID { get; set; }
        public decimal DFIN_VALUECOUNCIL { get; set; }
        public string DFIN_KEY { get; set; }
        public string DFIN_ART { get; set; }
        public string DFIN_EPI { get; set; }
        public decimal DFIN_ADMON_VALUE { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<FINES> FINES { get; set; }
    }
}
