//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opsControlCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINES
    {
        public decimal FIN_ID { get; set; }
        public decimal FIN_DFIN_ID { get; set; }
        public string FIN_NUMBER { get; set; }
        public string FIN_VEHICLEID { get; set; }
        public string FIN_MODEL { get; set; }
        public string FIN_MANUFACTURER { get; set; }
        public string FIN_COLOUR { get; set; }
        public Nullable<decimal> FIN_GRP_ID { get; set; }
        public Nullable<decimal> FIN_STR_ID { get; set; }
        public Nullable<decimal> FIN_STRNUMBER { get; set; }
        public System.DateTime FIN_DATE { get; set; }
        public string FIN_COMMENTS { get; set; }
        public Nullable<decimal> FIN_USR_ID { get; set; }
        public decimal FIN_UNI_ID { get; set; }
        public Nullable<decimal> FIN_DPAY_ID { get; set; }
        public Nullable<decimal> FIN_COD_ID { get; set; }
        public Nullable<decimal> FIN_SENT { get; set; }
        public Nullable<decimal> FIN_EXTRASENT { get; set; }
        public Nullable<decimal> FIN_FIN_ID { get; set; }
        public Nullable<decimal> FIN_GRP_ID_ZONE { get; set; }
        public Nullable<decimal> FIN_GRP_ID_ROUTE { get; set; }
        public Nullable<decimal> FIN_STATUS { get; set; }
        public decimal FIN_STATUSADMON { get; set; }
        public decimal FIN_STATUSADMONAUTO { get; set; }
        public decimal FIN_EXPORTED { get; set; }
        public string FIN_ERROR_EXP { get; set; }
        public string FIN_LETTER { get; set; }
        public decimal FIN_POSITION { get; set; }
        public string FIN_POLICENUMBER { get; set; }
        public Nullable<System.DateTime> FIN_CONFIRM_DATE { get; set; }
        public Nullable<decimal> FIN_LATITUDE { get; set; }
        public Nullable<decimal> FIN_LONGITUD { get; set; }
        public Nullable<decimal> FIN_NUM_PHOTOS { get; set; }
        public decimal FIN_NOTIFIED { get; set; }
    
        public virtual FINES_DEF FINES_DEF { get; set; }
        public virtual FINES_STATUS_DEF FINES_STATUS_DEF { get; set; }
        public virtual FINES_STSADMON_DEF FINES_STSADMON_DEF { get; set; }
        public virtual UNITS UNITS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
