//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opsControlCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINES_STSADMON_DEF
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public FINES_STSADMON_DEF()
        //{
        //    this.FINES = new HashSet<FINES>();
        //}
    
        public decimal DSAFIN_ID { get; set; }
        public string DSAFIN_DESCSHORT { get; set; }
        public string DSAFIN_DESCLONG { get; set; }
        public decimal DSAFIN_VERSION { get; set; }
        public decimal DSAFIN_VALID { get; set; }
        public decimal DSAFIN_DELETED { get; set; }
        public Nullable<decimal> DSAFIN_LIT_ID { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<FINES> FINES { get; set; }
    }
}
