//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opsControlCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINES_DEF_QUANTITY
    {
        public decimal DFINQ_ID { get; set; }
        public System.DateTime DFINQ_INIDATE { get; set; }
        public System.DateTime DFINQ_ENDATE { get; set; }
        public Nullable<decimal> DFINQ_YEAR { get; set; }
        public decimal DFINQ_VALUE { get; set; }
        public decimal DFINQ_VERSION { get; set; }
        public decimal DFINQ_VALID { get; set; }
        public decimal DFINQ_DELETED { get; set; }
        public decimal DFINQ_INI_MINUTE { get; set; }
        public decimal DFINQ_END_MINUTE { get; set; }
    }
}
