//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opsControlCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STREETS
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public STREETS()
        //{
        //    this.FINES = new HashSet<FINES>();
        //    this.UNITS = new HashSet<UNITS>();
        //}
    
        public decimal STR_ID { get; set; }
        public string STR_DESC { get; set; }
        public Nullable<decimal> STR_MIN { get; set; }
        public Nullable<decimal> STR_MAX { get; set; }
        public Nullable<decimal> STR_PROVINCIA { get; set; }
        public Nullable<decimal> STR_MUNICIPIO { get; set; }
        public string STR_TIPOVIA { get; set; }
        public decimal STR_VERSION { get; set; }
        public decimal STR_VALID { get; set; }
        public decimal STR_DELETED { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<FINES> FINES { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<UNITS> UNITS { get; set; }
    }
}
