//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opsControlCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadesInstalacion
    {
        public decimal idZona { get; set; }
        public string zona { get; set; }
        public decimal idSector { get; set; }
        public string sector { get; set; }
        public decimal UNI_ID { get; set; }
        public decimal UNI_DPUNI_ID { get; set; }
        public string UNI_DESCSHORT { get; set; }
        public string UNI_DESCLONG { get; set; }
        public decimal UNI_POSX { get; set; }
        public decimal UNI_POSY { get; set; }
        public Nullable<decimal> UNI_MAXSEATS { get; set; }
        public Nullable<decimal> UNI_STR_ID { get; set; }
        public string UNI_IP { get; set; }
        public string UNI_APPVERSION { get; set; }
        public string UNI_REPVERSION { get; set; }
        public decimal UNI_VERSION { get; set; }
        public decimal UNI_VALID { get; set; }
        public decimal UNI_DELETED { get; set; }
        public Nullable<System.DateTime> UNI_DATE { get; set; }
        public Nullable<decimal> UNI_DSTA_ID { get; set; }
        public Nullable<System.DateTime> UNI_DSTA_ID_FIRST_DATE { get; set; }
        public Nullable<decimal> UNI_MAIL_SENT { get; set; }
        public Nullable<decimal> UNI_USR_ID { get; set; }
    
        public string DSTA_DESCSHORT { get; set; }
        public decimal DALA_ID { get; set; }
        public Nullable<decimal> DALA_DALV_ID { get; set; }
        
        

    }
}
