//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opsControlCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.UNITS = new HashSet<UNITS>();
        }
    
        public decimal USR_ID { get; set; }
        public string USR_NAME { get; set; }
        public string USR_SURNAME1 { get; set; }
        public string USR_SURNAME2 { get; set; }
        public decimal USR_ROL_ID { get; set; }
        public string USR_LOGIN { get; set; }
        public string USR_PASSWORD { get; set; }
        public Nullable<decimal> USR_LAN_ID { get; set; }
        public bool USR_STATUS { get; set; }
        public Nullable<decimal> USR_CUS_ID { get; set; }
        public decimal USR_VERSION { get; set; }
        public decimal USR_VALID { get; set; }
        public decimal USR_DELETED { get; set; }
        public string USR_PASSWORD_PDA { get; set; }
    
        public virtual ROLES ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNITS> UNITS { get; set; }
    }
}
